### ISSUE TITLE
Implement LN encodings for all data types

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/rust-lnpbp#136]

**Comment by rajarshimaitra** [comment]
I am willing to take up this task. If you can provide a little elaboration on how it should be done, it would be helpful.

**Comment by rajarshimaitra** [comment]
To start with I have the following questions:

- Can we use the `Encode/Decode` trait in the `presentation` module? Or we need something else?
https://github.com/LNP-BP/rust-lnpbp/blob/380807a81469a72f233c5dcc2129141280e3318a/src/lnp/presentation/encoding.rs#L21-L32 

- What would be the difference between `StrictEncode` and LN-Encode? If they are the same for a specific prmitve, say `Vec<u8>`, can we use `StrictEncode` for underlying and wrap the parent structure in `LN-Encode`? This would also need me understanding the difference between two encodings so what's the best place to look for that? 

- Is it easier to just identify the difference between `StrictEncode` and `LN-Encode` and only implement `LN-Encode` for those structures where the difference matter and use `StrictEncode` for everything else?

**Comment by dr-orlovsky** [comment]
> Can we use the Encode/Decode trait in the presentation module?

Yes, that's why they were created, forgot about them. The difference of LN encoding with strict encoding and bitcoin consensus encoding is very simple: LN encoding is done according to BOLTs, bitcoin encoding according to Bitcoin Core code and strict encoding according to LNPBP standard (not published yet) with Peter Todd. Somewhere they are the same, somewhere they are different. No, Vec<u8> strict encoding will NOT work for LN, since LN uses BigInt for size encoding of the array, strict encoding always use u16, and bitcoin consensus uses VarInt. So the task is:
1. Implement different strategies for LN encoding (`FromBitcoin`, `FromStrict` etc - just see how it's done with strict encoding)
2. to check BOLT encoding and for those types which are encoded in the same way as in bitcoin consensus or strict encoding just apply the appropriate strategy
3. for the rest of types do a manual implementation according to BOLT encoding specs

**Comment by rajarshimaitra** [comment]
Thanks, this is clear now. Can you point to some BOLT specs where encoding is defined? That would be very helpful. Not all, just any pointer.

**Comment by rajarshimaitra** [comment]
Thoughts on structuring as I am thinking through it. How about we put an `ln_encoding` sub-module in the `paradigm` module next to `strict_encoding`? Which will contain the encoding of primitive types. Then we can have an `encoding` module in `lnp/presentation` that encodes primitive bitcoin datatypes. Does that sound ok?

This is also how `strict_encoding` of bitcoin primitives are done.

**Comment by rajarshimaitra** [comment]
For reference, rust-lightning does it like this with macros.
https://github.com/rust-bitcoin/rust-lightning/blob/4e82003261e11ece5d5fb3b13f686c9f7a0d2aaf/lightning/src/util/ser_macros.rs#L10

Corllary question: Isn't it better to use existing standard implementation of such primitve logics instead of inventing the wheel again?

**Comment by dr-orlovsky** [comment]
> So far it seems to me the this ln_encoding has to basically handle tlv-streams thus all the relevant data needs to be tlv encoded.

Not sure I follow logic here. Most of LN message data are not TLVs at all, the number of TLVs is just very few. And they follow the same encoding logic aside from TLV-specific type prefixes and lengths part, which will not be a part of LN encoding TLV structs, but not the rest

> BOLT1 specifies some basic types required here https://github.com/lightningnetwork/lightning-rfc/blob/master/01-messaging.md#fundamental-types.

Correct, we need these types + probably need to go through types used by LN messages in BOLT-2 and BOLT-7 and see which other types they are using (in message, not TLVs).

> I am curious though how much of the strict_encoding pattern I can use here.

You can use the pattern of how the strategy is used there and use this pattern to inherit either Bitcoin consensus or strict encoding for the types where they match LN rules (no idea how many of them are out there)

> Corllary question: Isn't it better to use existing standard implementation of such primitve logics instead of inventing the wheel again?

This is TLVs and I do not see any reason to use poor design on implementing logic with macros and not generics

**Comment by rajarshimaitra** [comment]
Extending my answer on IRC. It seems after BigSize (which is already merged), there not much to do with encoding. We need to handle various msg types which will be handled separately including TLVs. The BOLTs doesn't specify any other basic encoding format. All the rest of the data are big-endian byte serialized. I think there we can even have `strict_encode` representation within msg formats and tlvs to write the objects on wire. But that will make lnp-node incompatible with other nodes. 

 Let me know if I am missing anything.

**Comment by dr-orlovsky** [comment]
I assume at least you have to encode public keys, signarutes, hashes, hash preimages etc, etc, which is a set of types. Even if it is simple, we do not yet have it.

> I think there we can even have strict_encode representation within msg formats and tlvs to write the objects on wire. Because encoding decoding will be handled internally. But that will make lnp-node incompatible with other nodes.

That is why we need LN encoding and that is the reason behind this issue :)

**Comment by rajarshimaitra** [comment]
>I assume at least you have to encode public keys, signarutes, hashes, hash preimages etc, etc, which is a set of types. Even if it is simple, we do not yet have it.

Isn't all of these things already have standard encoding defined on these structure? For example, for public key and signatures they already have compressed/DER encoding formats. Hashes can be told to give their underlying bytes. Or do we want to combine all of these methods in a separate encoding like LN-encode? 

>That is why we need LN encoding and that is the reason behind this issue :)

Even if we write our own LN-encode it might still not be compatible with other nodes.

I guess what we are looking for here is some uniform API that does the encoding for all these data types, instead of calling their individual methods. Is that correct?
