### ISSUE TITLE
CI: add crate publication workflow

### ISSUE THREAD

**Issue by zoedberg** [LNP-BP/rust-lnpbp#142]
As discussed, we should add crate publication triggered by git tags (starting with `v`) for these projects:
- [ ] `rust-lnpbp`
- [x] `rgb-node`
- [x] `lnp_node`
- [x] `rust-amplify`
- [x] `bitcoin_num`

Please let me know if I forgot any project

**Comment by dr-orlovsky** [comment]
Electrum didn't is a fork which we do not maintain and can't publish. Otherwise you listed them all
