### ISSUE TITLE
Is `stringify!` what we really want here?

### ISSUE THREAD

**Issue by afilini** [LNP-BP/rust-lnpbp#17]
https://github.com/LNP-BP/rust-lnpbp/blob/master/src/bp/tagged256.rs#L36

The macro is unused so I can't say for sure what it's meant to do, but that looks wrong to me. From the [docs](https://doc.rust-lang.org/std/macro.stringify.html): "This macro will yield an expression of type &'static str which is the stringification of all the tokens passed to the macro. No restrictions are placed on the syntax of the macro invocation itself.".

Kinda dangerous because it wouldn't make anything fail in an obvious way, but it would be a mess to remove in the future.

I would just remove the `stringify` and concat `$prefix` and `$tag`.

**Comment by dr-orlovsky** [comment]
It's not working like that, compiler produces "only literals (like `"foo"`, `42` and `3.14`) can be passed to `concat!()`"

**Comment by dr-orlovsky** [comment]
It happened that this was somehow fixed
