### ISSUE TITLE
Duplicated type id in Rgb1

### ISSUE THREAD

**Issue by afilini** [LNP-BP/rust-lnpbp#27]
https://github.com/LNP-BP/rust-lnpbp/blob/ed4fdb314f46e409d1a8f6d93658bfbc352d0d9e/src/rgb/schemata/fungible.rs#L99

https://github.com/LNP-BP/rust-lnpbp/blob/ed4fdb314f46e409d1a8f6d93658bfbc352d0d9e/src/rgb/schemata/fungible.rs#L114

**Comment by dr-orlovsky** [comment]
Thanks for reporting. I see the fix included in #28

**Comment by dr-orlovsky** [comment]
With the introduction of new schema (with pre-defined type ids) the issue become outdated
