### ISSUE TITLE
Use more "rusty" Error types

### ISSUE THREAD

**Issue by Kixunil** [LNP-BP/rust-lnpbp#32]
I noticed that `InetAddr` as well as other types use `String` to report errors. This is generally viewed as anti-pattern, especially in library code. I suggest to use custom error types.

We can decrease boilerplate in the early stage of development by using crates [`thiserror`](https://crates.io/crates/thiserror) and [`anyhow`](https://crates.io/crates/anyhow) using this pattern:

```rust
#[derive(Debug, Error)]
#[thiserror(transparent)] // NOT to be confused with repr(transparent)!!! completely different things
struct InetAddrError(anyhow::Error);
```

This way we will not waste time writing custom enums that we aren't confident about, but avoid running into technical debt of rewriting code to use something else than strings later. The dependencies can be removed at any point and replaced with manual implementation without loss of features or compatibility.

Important: we must **not** `impl From<anyhow::Error> for InetAddrError` as that would make the type forward-incompatible.

I might be able to help with this.

**Comment by dr-orlovsky** [comment]
Probably I will just construct proper Error structure; thank you for pointing that out. Would not like to proliferate library dependencies for such a boilerplate case.
