### ISSUE TITLE
There's a use-tor feature, but torut is NOT optional

### ISSUE THREAD

**Issue by Kixunil** [LNP-BP/rust-lnpbp#35]
This causes the library to download and compile the crate even if it's not being used.

Suggestion: make the crate optional and use its name instead of feature in `#[cfg()]`

**Comment by dr-orlovsky** [comment]
Looks like `optional` in `Cargo.toml` will be sufficient for this, since I expect there might be more Tor-related things in the future not dependent on `torut` (or may be we'll use other Tor library)

**Comment by Kixunil** [comment]
Good point about not tying it to `torut`. `use-tor` will need to depend on `torut` too. And we should document that `torut` is unstable feature. There's a new Cargo feature planned that will make this more explicit at some point by splitting namespaces of futures and dependencies.
