### ISSUE TITLE
Consider decreasing use of wildcards in use statements

### ISSUE THREAD

**Issue by Kixunil** [LNP-BP/rust-lnpbp#36]
Use statements containing wildcards (e.g. `use foo::*`) have a significant disadvantage: it makes it very hard to understand where an item is coming from, especially for new people.

For example, when written as:

```rust
use foo::*;
use bar::*;

let baz = Baz::new();
```

It's impossible to know where `Baz` comes from without using search tool. However from:

```rust
use foo::Something;
use bar::Baz;

let baz = Baz::new();
```

We can easily see `Baz` is in `bar`.

Further, this could cause various issues like two developers adding an item with same name in different modules causing conflict in a third module after merge, which can not happen with explicit `use` statements.

As an alternative, limit the scope of asterisks to where they're needed. Eg.g sometimes it's useful to `use LongEnumNameWithManyVariants::*;` at the top of a function containing a huge `match`.

**Comment by dr-orlovsky** [comment]
Agree
