### ISSUE TITLE
Use 32-bit integers for transaction output indexes in single-use seals

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/rust-lnpbp#45]
Bitcoin normally uses VarInt to represent the number of transaction outputs that may be contained in a given transaction and 32-bit integer to reference specific transaction output from other's transaction input. While with the given block size limit transaction containing more than 2^16 outputs can't fit the block, it's better not to diverge from bitcoin data structure. The original reason why 16-bit integers were introduced is to save some storage space for RGB client-validated data; however bitcoin transaction output single-use seals are more generic standard and RGB consensus commitment encoding does not require storage space optimization. RGB P2P protocols and vendor-specific RGB storage may still use 16-bit integers; however this should not be required by the LNP/BP standards.

**Comment by rajarshimaitra** [comment]
Is this issue still open? I am willing to work on it, if it is.

**Comment by dr-orlovsky** [comment]
It is opened, you are welcome!

**Comment by rajarshimaitra** [comment]
To make sure that I understand correctly. The concerning index here is `vout` right? which is 16 bits and needs to be changed to 32 bits. 
https://github.com/LNP-BP/rust-lnpbp/blob/dbd0d324bf7762e8ddb7c88393ad70df5a96dc6e/src/bp/blind.rs#L25-L35

**Comment by dr-orlovsky** [comment]
Correct
