### ISSUE TITLE
Use 64-bit blinding factors for transaction outpus

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/rust-lnpbp#51]
According to https://github.com/LNP-BP/LNPBPs/issues/33

**Comment by rajarshimaitra** [comment]
Is this issue still open? I am willing to work on it if not already done.

**Comment by dr-orlovsky** [comment]
It is, you are welcome to take it!

**Comment by rajarshimaitra** [comment]
Ok. Just to confirm that the issue is talking about this blinding factor right? 
https://github.com/LNP-BP/rust-lnpbp/blob/2f6fee732417aad5c71fcd0120ed0db4b1e61061/src/bp/blind.rs#L28

Let me know if there are other such factors that need update too and I am missing.

**Comment by dr-orlovsky** [comment]
Hi! Yes, we are talking about it. I am seeing your PR already, will review it there.
