### ISSUE TITLE
Refactor: Move `enum ScriptPubkeyComposition` to `dbc/types.rs`

### ISSUE THREAD

**Issue by rajarshimaitra** [LNP-BP/rust-lnpbp#59]
If this has been already discussed or kept here for future purposes, feel free to close this issue.

`ScriptPubkeyComposition` is a major input in the high level `TxCoinatianer`, which is subsequently passed down into smaller containers. So it feels to me that a better location for `ScriptPubkeyComposition` is with the other protocol level primitive types like `Proof` and `ScriptInfo`. Currently, its located in `dbc/scriptpubkey.rs`. 

Thus proposing to reallocate this enum with other primitive types.

**Comment by dr-orlovsky** [comment]
Agree. Can you do this?

**Comment by rajarshimaitra** [comment]
Will work on it.

**Comment by dr-orlovsky** [comment]
Yeah, good point

**Comment by dr-orlovsky** [comment]
After careful consideration decided that `types` must hold generic DBC types (`Proof`, `Supplement`), while everything specific to `scriptPubkey` commitments must be in the same mod.
