### ISSUE TITLE
Versioning for non-commitment RGB data structures

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/rust-lnpbp#63]
While with those data structures that participate in commitments we can't use versioning without risking complex hard-fork issues under client-side validation paradigm, we can (and should) have versioning for network/storage serialized data, like consignments and disclosures.

TODO: Add version field to consignments and disclosures, defaulting now to 1

**Comment by rajarshimaitra** [comment]
Noted. Started working on it.

**Comment by dr-orlovsky** [comment]
Closing, since it happens to be already there :)
