### ISSUE TITLE
Complete merklization & concealments for RGB node commit-encoding

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/rust-lnpbp#97]
Right now commit-encode procedure for RGB nodes just uses strict serialization of all the data. Move to the merklization and conceal algorithm for both metadata and assignments.

**Comment by rajarshimaitra** [comment]
Not sure what I am missing, but isn't assignments and metadata are already commit encoded with merklization?

**Comment by dr-orlovsky** [comment]
Yeah, seems at some point I closed this issue and forgot to reference it from the commit. Will look which commit it was
