### ISSUE TITLE
Investigate possibility of using bulletproofs from Monero

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/rust-lnpbp#99]

**Comment by dr-orlovsky** [comment]
Have forgot that Monero uses different elliptic curve, so we are uncompatible and can't use Bulletproof implementation from there.

**Comment by BitcoinErrorLog** [comment]
Asking fluffypony if he has anything to add

**Comment by fluffypony** [comment]
FYI: whilst all of the cool stuff with Bulletproofs now is being done on x25519 / Ristretto, the original reference implementation was on secp256k1, so I'd suggest grabbing that.

**Comment by fluffypony** [comment]
Reference implementation is here: https://github.com/bbuenz/BulletProofLib

And this should have a more recent, maintained Bulletproofs implementation for secp256k1 in it: https://github.com/ElementsProject/secp256k1-zkp

**Comment by fluffypony** [comment]
I take that last one back, looks like CT is in it but not Bulletproofs.

**Comment by dr-orlovsky** [comment]
Thank you, @fluffypony . Can you point out what you are calling the original reference implementation? The one from Monero team or some other work?

What I have found is https://github.com/moneromooo-monero/bitmonero/blob/bp-multi-aggregation/src/ringct/bulletproofs.h and https://ostif.org/wp-content/uploads/2018/10/OSTIF-QuarksLab-Monero-Bulletproofs-Final2.pdf

**Comment by fluffypony** [comment]
@dr-orlovsky in case you missed it I posted links above :)

**Comment by dr-orlovsky** [comment]
@fluffypony yeah, Andrew Poelstra told me that they already have a long-standing PR to zkp-version of libsecp256k1 in ElementsProject — https://github.com/ElementsProject/secp256k1-zkp/pull/23 — and they plan to merge it at some point later, hopefully this year. And that Grin rust implementation have diverged from the spec and is incompatible.
